"""
Django settings for _project_ project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path
from environ import Env


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


Env.read_env(BASE_DIR / '.env')
env = Env(
	DEBUG = (bool, False),
	LOGS_DIR = (str, 'logs')
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

INTERNAL_IPS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',

	# Libs
	'solo',

	# This project
	'core'
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_project_.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'templates'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = '_project_.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {'default': env.db()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Samara'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_ROOT  = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging             vvv для аннотации
LOGS_DIR = BASE_DIR / str(env('LOGS_DIR'))

if not LOGS_DIR.exists():
	LOGS_DIR.mkdir(parents = True)

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False, # Отключить иные обработчики

	'formatters': {
		'standart': {
			'format': '[{levelname}] {asctime} {name}:{lineno} {funcName}() {message}',
			'style': '{',
			'datefmt': '%Y-%m-%d %H:%M:%S',
		},
	},

	'handlers': {
		'console': {
			'level': 'DEBUG' if DEBUG else 'INFO',
			'class': 'logging.StreamHandler',
			'formatter': 'standart',
		},
		'file': {
			'level': 'INFO',
			'class': 'logging.FileHandler',
			'formatter': 'standart',
			'filename': LOGS_DIR / f'logs.log'
		},
	},

	'root': {
		'handlers': ['console', 'file'],
		'level': 'DEBUG' if DEBUG else 'INFO'
	}
}
if not 'runserver' in sys.argv:
	# Чтобы не спамило дебаг логами при миграциях
	LOGGING['root']['level'] = 'INFO'

# MARK: Для AdminModelRegistartor
DEFAULT_MODEL_ADMIN_CLASSES = {
	'solo.models.SingletonModel': 'solo.admin.SingletonModelAdmin'
}



# MARK: Libs
PHONENUMBER_DEFAULT_REGION = "RU" # Код страны (ISO 3166-1 alpha-2)
