# Generated by Django 5.2.5 on 2025-09-24 10:15

import django.db.models.deletion
import pathlib
import phonenumber_field.modelfields
import shared.models.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Первый номер телефона')),
                ('secondary_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Второй номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Эл. почта')),
                ('addres', models.CharField(blank=True, max_length=128, verbose_name='Адрес')),
                ('work_time_text', models.CharField(blank=True, max_length=32, verbose_name='Время работы')),
                ('map_coordinates', models.CharField(blank=True, help_text='Формат: <code>53.556350, 49.216210</code>', max_length=32, validators=[shared.models.validators.map_coordinates_format], verbose_name='Координаты на карте')),
            ],
            options={
                'verbose_name': '📠 | Контакты компании',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется для HTML Title и H1.', max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('h1_override', models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок (переопределение)')),
                ('html_title_override', models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)')),
                ('html_description', models.CharField(blank=True, verbose_name='HTML Description')),
                ('is_generic_page', models.BooleanField(default=False, help_text='✅: Будет автоматически доступно по указанному url, требует заданного <code>template_name</code>. Используйте для простых страниц, не требующих своего View.<br>❌: Выбирайте, когда для обработки страницы нужно использовать кастомный view.<br><br>Влияет на работу логики поля <code>URL path</code> & <code>template_name</code>.', verbose_name='Это динамически-добавляемая страница?')),
                ('template_name', models.CharField(blank=True, help_text='<code>is_generic_page:</code>✅ - Путь к файлу, включая расширение, <b>должно быть установленно</b>.<br><code>is_generic_page:</code>❌ - Игнорируется, потому <b>должно быть</b> пустым.', validators=[shared.models.validators.template_with_this_name_exists], verbose_name='Название django-темплейта')),
                ('url_source', models.CharField(blank=True, help_text='<details style="padding-left: 1rem;"><summary style="margin-left: -1rem;"><code>is_generic_page</code>: ✅</summary>Полный URL путь, по которому будет доступна страница. Указав <code>info/about-us/</code> здесь, страница будет доступна по абсолютному пути <code>/info/about-us/</code><br><code>get_absolute_url()</code> вернёт <code>"/info/about-us/"</code>.<br><b><u>Крайне рекомендуется</u></b> создавать url <u>на основе <code>slug</code></u>. Например, при slug = <code>about-us</code>, url = <code>info/about-us/</code>).<br><br></details><details style="padding-left: 1rem;"><summary style="margin-left: -1rem;"><code>is_generic_page</code>: ❌</summary>View name того view, который обрабатывает эту страницу.<br>Например, в <code>urlpatterns</code> указан <code>path("fun-path/", ..., name="your-name")</code>, тут указываете <code>"your-name"</code>.<br><code>get_absolute_url()</code> вернёт <code>"/fun-path/"</code>.</details><br>Используется для получения url страницы в методе <code>get_absolute_url()</code>.<br>Также значение в этом поле валидируется и проходит проверку на корректность.', max_length=64, unique=True, verbose_name='URL Source')),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Поддерживается django template рендеринг!<details style="width: 70%; padding-left: 1rem;"><summary style="margin-left: -1rem;">Подробнее</summary>\n\t\tЕсли активирован рендеринг, текст из этого поля будет обработан через django template рендеринг.<br>\n\t\tЭто означает, что вы можете использовать здесь темплейт инструменты, такие как:\n\t\t<li>Теги <code>{% if %}</code>, <code>{% for %}</code> и другие.</li>\n\t\t<li>\n\t\t\tПеременные, например: <code>{{ page.extra_context }},\n\t\t\t{{ global.pages.home }}, {{ global.extra_context }}</code> и т.д.\n\t\t</li>\n\t\t<li>\n\t\t\tА также теги обработки, например: <code>...|default:"..."</code>,\n\t\t\t <code>...|truncatechars:40</code> и многие другие.\n\t\t</li>\n\t\tКонтекст будет такой же, как и на странице, на которой будет выводится этот текст.<br>\n\n\t\tВажно: функционал рендеринга реализуется в каждом темплейте отдельно, через специальный template-тег.\n\t\tЭто означает, что <b>нет гарантии</b>, что фронтендер добавил эту обработу <i>там</i>.\n\t\tСогласуйте это вместе с фронтендером.<br>Если же вы используете стандартный темплейт <code>core/generic/page.html</code>, то рендеринг гарантирован.</details>', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'страницы',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/_b.VV/my-projects/TLTConvectorTraining/media/favicon'))),
                ('robots_txt_content', models.TextField(blank=True, verbose_name='Содержимое Robots.txt')),
                ('head_script', models.TextField(blank=True, help_text='Этот текст будет вставлен в блок &ltscript&gt в &lthead&gt каждой html-страницы сайта', verbose_name='Скрипт')),
            ],
            options={
                'verbose_name': '⚙ | Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TelegramSendingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_env_name', models.CharField(help_text='Название ENV переменной с токеном этого бота. Также проверяется существование токена в телеграм системе.', validators=[shared.models.validators.env_variable_name], verbose_name='ENV-переменная с токеном')),
                ('chat_id', models.CharField(help_text='Если был передан некорректный ID чата - ошибка возникнет только при первой попытке отправить сообщение, будте внимательны!', max_length=32, verbose_name='ID чата')),
                ('specialization', models.CharField(choices=[('new_request_notifications', 'Уведомления о новых заявках'), ('logs', 'Логи')], help_text='Может быть только один канал для конкретной специализации', unique=True, verbose_name='Специализация канала')),
            ],
            options={
                'verbose_name': 'Канал отправки сообщений в Telegram',
                'verbose_name_plural': '📡 | Каналы отправки сообщений в Telegram',
            },
        ),
        migrations.CreateModel(
            name='ExtraContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('value', models.CharField(verbose_name='Значение')),
                ('page', models.ForeignKey(blank=True, help_text='Если указать здесь страницу - ключ будет доступен через объект страницы и будет исключён из глобального контекста (<code>global.extra_context</code>).<br>Тем не менее, он всё также будет доступен глобально, но уже через <code>global.pages</code>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_context_manager', to='core.page', verbose_name='Привязать к странице')),
            ],
            options={
                'verbose_name': 'Дополнительный контекст',
                'verbose_name_plural': 'Дополнительный контекст',
            },
        ),
    ]
