# Generated by Django 5.2.6 on 2025-09-25 07:55

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyContacts',
            new_name='CompanyInfo',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='JBrony Site', help_text='В основном используется в base.html', max_length=128, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/_b.VV/commercial-projects/TTSTempering/media/favicon')),
        ),
    ]
