# Generated by Django 5.2.5 on 2025-08-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracontext',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Если указать здесь страницу - ключ будет доступен через объект страницы и будет исключён из глобального контекста (<code>global.extra_context</code>).<br>Тем не менее, он всё также будет доступен глобально, но уже через <code>global.pages</code>', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_context_manager', to='core.page', verbose_name='Привязать к странице'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='Уникальный ID страницы', max_length=32, unique=True, verbose_name='Slug'),
        ),
    ]
