# Generated by Django 5.2.6 on 2025-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_page_last_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_generic_page',
            field=models.BooleanField(default=False, help_text='✅: Будет автоматически доступно по url <code>"/<slug>/"</code>, требует заданного <code>Template name</code>. Используйте для простых страниц, которым не нужен свой View.<br>❌: Выбирайте, когда для обработки страницы нужно использовать кастомный View.<br><br>Влияет на логику работы полей <code>URL Pathname</code> и <code>Template name</code>.', verbose_name='Это динамически-добавляемая страница?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url_source',
            field=models.CharField(blank=True, help_text='<code>is_generic_page:</code>✅ - Игнорируется, потому <b>должно быть</b> пустым.<br><code>is_generic_page:</code>❌ - Pathname того url path, который обрабатывает эту страницу.<details style="padding-left: 1rem;">Например, в <code>urlpatterns</code> есть <code>path("fun-path/", some_view, name="your-name")</code>, тут указываете <code>"your-name"</code>.<br>Тогда, метод <code>get_absolute_url()</code> вернёт ссылку на этот path, т.е <code>"/fun-path/"</code>.<br><br>Для index страницы по полному пути "/", а также для generic страниц с кастомным URL в принципе, увы, но вы вынуждены создать свой path и view, даже если ей не нужна дополнительная логика.</details>', max_length=64, unique=True, verbose_name='URL Pathname'),
        ),
    ]
