# Generated by Django 5.2.4 on 2025-08-05 10:31

import pathlib
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mysecondarymodel_mysingletonmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitersContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_contact_link', models.URLField(blank=True, verbose_name='Telegram')),
                ('vk_contact_link', models.URLField(blank=True, verbose_name='Вконтакте')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('addres', models.CharField(blank=True, max_length=128, verbose_name='Адрес')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_favicon', models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/icons'), verbose_name='Favicon сайта')),
                ('robots_txt_content', models.TextField(blank=True, verbose_name='Содержимое Robots.txt')),
                ('html_head_addition', models.TextField(blank=True, help_text='Этот текст будет вставлен в конец в указанного тега на каждой html странице сайта', verbose_name='Добавить в <head>')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='MySecondaryModel',
        ),
        migrations.DeleteModel(
            name='MySingletonModel',
        ),
    ]
