# Generated by Django 5.2.5 on 2025-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_extracontext_page_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracontext',
            name='value',
            field=models.CharField(verbose_name='Значение'),
        ),
    ]
