# Generated by Django 5.2.4 on 2025-08-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recruiterscontacts_sitesettings_delete_mymodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecruitersContacts',
            new_name='CompanyContacts',
        ),
        migrations.AlterModelOptions(
            name='companycontacts',
            options={'verbose_name': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта'},
        ),
    ]
