# Generated by Django 5.2.5 on 2025-08-15 08:06

import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_extracontext_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontacts',
            name='map_coordinates',
            field=models.CharField(default='53.556350, 49.216210', help_text='Формат: <code>53.556350, 49.216210</code>', max_length=32, validators=[shared.models.validators.map_coordinates_format], verbose_name='Координаты на карте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='is_generic_page',
            field=models.BooleanField(default=True, help_text='✅: Будет автоматически доступно по указанному url. Используйте для страниц без логики.<br>❌: Выбирайте, когда для обработки страницы нужно использовать кастомный view.<br>Влияет на работу логики поля <code>URL path</code>. ', verbose_name='Это динамически-генерируемая страница?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url_path',
            field=models.CharField(blank=True, help_text='<details><summary><code>is_generic_page</code>: ✅</summary>URL путь, по которому будет доступна страница. Указав <code>info/about-us/</code> здесь, страница будет доступна по адресу <code>$site.$domain/info/about-us/</code>.<br><b><u>Крайне рекомендуется</u></b> создавать url <u>на основе slug</u>. Например, при slug = <code>about-us</code>, url = <code>info/about-us/</code>).<br></details><details><summary><code>is_generic_page</code>: ❌</summary>Название <b>должно</b> соответствовать адресу, по которому можно перейти на страницу по кастомному view.<br>При ненахождении страницы по указанному url - сохранить изменения / создать страницу не удастся.<br></details><br><b>Всегда</b> отражает реальный адрес страницы.', max_length=64, unique=True, validators=[shared.models.validators.StringStartswith('/', invert=True), shared.models.validators.StringEndswith('/')], verbose_name='URL путь'),
        ),
    ]
