# Generated by Django 5.2.6 on 2025-09-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_page_url_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url_source',
            new_name='url_path_name',
        ),
    ]
