# Generated by Django 5.2.5 on 2025-08-15 08:09

import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companycontacts_map_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontacts',
            name='map_coordinates',
            field=models.CharField(blank=True, help_text='Формат: <code>53.556350, 49.216210</code>', max_length=32, validators=[shared.models.validators.map_coordinates_format], verbose_name='Координаты на карте'),
        ),
    ]
