# Generated by Django 5.2.4 on 2025-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='Description', max_length=32, verbose_name='HTML Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='Title', max_length=32, verbose_name='HTML Title'),
            preserve_default=False,
        ),
    ]
