# Generated by Django 5.2.6 on 2025-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_url_source_page_url_path_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url_path_name',
            field=models.CharField(blank=True, help_text='<code>is_generic_page:</code>✅ - Игнорируется, потому <b>должно быть</b> пустым.<br><code>is_generic_page:</code>❌ - <code>name</code> того url path, который обрабатывает эту страницу.<details style="padding-left: 1rem;">Например, в ваших <code>urlpatterns</code> есть <code>path("fun-path/", some_view, name="your-name")</code>, тут указываете <code>"your-name"</code>.<br>Вы всё корретно указали, метод <code>get_absolute_url()</code> вернёт ссылку на этот path, т.е <code>"/fun-path/"</code>.<br><br>Для index страницы по полному пути "/", а также для generic страниц с кастомным URL в принципе, увы, но вы вынуждены создавать свои path и view, даже если не нужна дополнительная логика.</details>', max_length=64, verbose_name='URL Pathname'),
        ),
    ]
