# Generated by Django 5.2.5 on 2025-08-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_companycontacts_map_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramsendingchannel',
            old_name='channel_specialization',
            new_name='specialization',
        ),
    ]
