# Generated by Django 5.2.5 on 2025-08-18 06:08

import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_channel_specialization_telegramsendingchannel_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='site_favicon',
            new_name='favicon',
        ),
        migrations.AlterField(
            model_name='telegramsendingchannel',
            name='token_env_name',
            field=models.CharField(help_text='Название ENV переменной с токеном этого бота.<br>Проведётся проверка существования токена в Telegram. В ситуации невозможности провести проверку - валидация пройдёт с предупреждением о возможных ошибках в будущем.', validators=[shared.models.validators.env_variable_name], verbose_name='ENV-переменная с токеном'),
        ),
    ]
