# Generated by Django 5.2.4 on 2025-08-05 12:58

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_page_description_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestener_name', models.CharField(max_length=24, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('comment', models.TextField(max_length=2048, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения заявки')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
            },
        ),
    ]
