# Generated by Django 5.2.6 on 2025-09-29 10:57

import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_page_url_path_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html_description',
            field=models.TextField(blank=True, verbose_name='HTML Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_name',
            field=models.CharField(blank=True, help_text='<code>is_generic_page:</code>✅ - Путь к файлу, включая расширение. По умолчанию используется <code>core/generic/page.html</code><br><code>is_generic_page:</code>❌ - Игнорируется, потому <b>должно быть</b> пустым.', validators=[shared.models.validators.template_exists_in_root_directory], verbose_name='Название django-темплейта'),
        ),
    ]
