# Generated by Django 5.2.4 on 2025-08-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_feedbackrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackRequest',
        ),
    ]
