# Generated by Django 5.2.6 on 2025-09-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_page_html_description_alter_page_template_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='h1_override',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='html_title_override',
            new_name='html_title',
        ),
    ]
