# Generated by Django 5.2.5 on 2025-08-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_site_favicon_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='favicon'),
        ),
    ]
