# Generated by Django 5.2.6 on 2025-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_h1_override_page_h1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='h1',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_title',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title'),
        ),
    ]
