# Generated by Django 5.2.5 on 2025-08-07 07:06

import ckeditor.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_feedbackrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycontacts',
            options={'verbose_name': 'Контакты компании'},
        ),
        migrations.RemoveField(
            model_name='companycontacts',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='companycontacts',
            name='tg_contact_link',
        ),
        migrations.RemoveField(
            model_name='companycontacts',
            name='vk_contact_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='html_head_addition',
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='first_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Первый номер телефона'),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='secondary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Второй номер телефона'),
        ),
        migrations.AddField(
            model_name='companycontacts',
            name='work_time_text',
            field=models.CharField(blank=True, max_length=32, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='page',
            name='ceo_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Основное наполнение страницы', verbose_name='CEO контент'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_name',
            field=models.CharField(default='page', help_text='Зачастую будет использоваться в <h1> на страницах', max_length=64, verbose_name='Название страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='head_script',
            field=models.TextField(blank=True, help_text='Этот текст будет вставлен в блок <script> в <head> каждой html-странице сайта', verbose_name='Добавить в <head>'),
        ),
        migrations.AlterField(
            model_name='companycontacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Эл. почта'),
        ),
    ]
