# Generated by Django 5.2.5 on 2025-08-20 09:03

import pathlib
import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sitesettings_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/favicon')),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='head_script',
            field=models.TextField(blank=True, help_text='Этот текст будет вставлен в блок &ltscript&gt в &lthead&gt каждой html-страницы сайта', verbose_name='Скрипт'),
        ),
        migrations.AlterField(
            model_name='telegramsendingchannel',
            name='chat_id',
            field=models.CharField(help_text='Если был передан некорректный ID чата - ошибка возникнет только при первой попытке отправить сообщение, будте внимательны!', max_length=32, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='telegramsendingchannel',
            name='token_env_name',
            field=models.CharField(help_text='Название ENV переменной с токеном этого бота. Также проверяется существование токена в телеграм системе.', validators=[shared.models.validators.env_variable_name], verbose_name='ENV-переменная с токеном'),
        ),
    ]
