# Generated by Django 5.2.5 on 2025-08-07 08:08

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_companycontacts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/favicon'), verbose_name='Favicon сайта'),
        ),
    ]
