# Generated by Django 5.2.6 on 2025-09-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_page_h1_alter_page_html_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='add_sitename_to_html_title',
            field=models.BooleanField(default=True, verbose_name='Добавить название сайта к HTML Title?'),
        ),
    ]
