# Generated by Django 5.2.5 on 2025-08-20 09:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='ceo_content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='h1',
            field=models.CharField(blank=True, max_length=127, verbose_name='H1 Заголовок'),
        ),
    ]
