# Generated by Django 5.2.6 on 2025-10-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_page_add_sitename_to_html_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order'], 'verbose_name': 'страница', 'verbose_name_plural': 'страницы'},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
