# Generated by Django 5.2.5 on 2025-08-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_page_ceo_content_alter_page_h1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='ceo_content',
            new_name='сontent',
        ),
    ]
