# Generated by Django 5.2.5 on 2025-08-07 12:45

import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sitesettings_site_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template_name',
            field=models.CharField(default='f', help_text='Путь к файлу .html', validators=[shared.models.validators.TemplateWithThisNameExists.validator], verbose_name='Название django-темплейта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(help_text='Используется при рендеринге, в основном используется в заголовках <h1>', max_length=64, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='head_script',
            field=models.TextField(blank=True, help_text='Этот текст будет вставлен в блок &ltscript&gt в <head> каждой html-странице сайта', verbose_name='Добавить в <head>'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, upload_to='favicon', verbose_name='Favicon сайта'),
        ),
    ]
