# Generated by Django 5.2.5 on 2025-08-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_ceo_content_page_сontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='сontent',
            new_name='content',
        ),
    ]
