# Generated by Django 5.2.5 on 2025-08-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_page_template_name_alter_page_page_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='html_title',
        ),
        migrations.AddField(
            model_name='page',
            name='h1',
            field=models.CharField(default='s', help_text='Обычно используется в &lth1&gt заголовке', max_length=128, verbose_name='Главный заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(max_length=64, verbose_name='Название страницы'),
        ),
    ]
