# Generated by Django 5.2.6 on 2025-10-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_page_url_path_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url_path_name',
            new_name='url_name',
        ),
    ]
