# Generated by Django 5.2.5 on 2025-08-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_сontent_page_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='сontent',
        ),
    ]
