# Generated by Django 5.2.5 on 2025-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_content_page_сontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, verbose_name='HTML Description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_title',
            field=models.CharField(blank=True, help_text='По умолчанию для формирования HTML Title используется verbose_name.Укажите здесь свой title, и он будет использован вместо него.', max_length=127, verbose_name='HTML Title override'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='verbose_name',
            field=models.CharField(help_text='По умолчанию также используется и для формирования HTML Title', max_length=127, verbose_name='Человеко-читаемое имя'),
        ),
    ]
