# Generated by Django 5.2.6 on 2025-10-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_url_path_name_page_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
