# Generated by Django 5.2.5 on 2025-08-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_page_description_alter_page_html_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='description',
            new_name='html_description',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='html_title',
            new_name='html_title_override',
        ),
    ]
