# Generated by Django 5.2.5 on 2025-08-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_description_page_html_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='verbose_name',
            new_name='name',
        ),
    ]
