# Generated by Django 5.2.5 on 2025-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_verbose_name_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для формирования HTML Title используется verbose_name.Укажите здесь свой title, и он будет использован вместо него.', max_length=128, verbose_name='HTML Title override'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется и для формирования HTML Title', max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
