# Generated by Django 5.2.5 on 2025-08-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_page_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='сontent',
            new_name='content',
        ),
    ]
