# Generated by Django 5.2.5 on 2025-08-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_сontent_page_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='h1',
            new_name='h1_override',
        ),
    ]
