# Generated by Django 5.2.5 on 2025-08-22 05:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_h1_page_h1_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Будет отрендерено через django-template обработку. Это значит, что вы можете использовать {% if %}, {% for %} и другие теги.<br>Будет использован <b>глобальный</b> контекст, т.е общий с html темплейтами.', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. ', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_generic_page',
            field=models.BooleanField(default=True, help_text='✅: Будет автоматически доступно по указанному url. Используйте для страниц без логики.<br>❌: Выбирайте, когда для обработки страницы нужно использовать кастомный view.<br>Влияет на работу логики поля <code>URL path</code>.', verbose_name='Это динамически-генерируемая страница?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется для HTML Title и H1.', max_length=64, verbose_name='Название'),
        ),
    ]
