# Generated by Django 5.2.5 on 2025-08-26 07:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_page_render_content_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Будет отрендерено через <code>django-template</code> обработку. Это значит, что вы можете обращаться к переменным (напр. <code>{{ page }}</code>) использовать теги <code>{% if %}</code>, <code>{% for %}</code>, и другие.<br>Будет использован <b>глобальный</b> контекст, т.е тот же, что доступен в самих темплейтах.<br>', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='render_content',
            field=models.BooleanField(default=True, help_text='Отключите рендеринг content, если это вызывает ошибки. Включено по умолчанию потому, что в 99.99% случаев оно НЕ создаёт проблем.', verbose_name='Использовать рендеринг для content?'),
        ),
    ]
