# Generated by Django 5.2.5 on 2025-08-27 09:59

import ckeditor.fields
import shared.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_page_content_alter_page_render_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='При включённом рендеринге, это будет отрендерено через <code>django-template</code> обработку. Это значит, что вы можете обращаться к переменным (напр. <code>{{ page }}</code>) использовать теги <code>{% if %}</code>, <code>{% for %}</code>, и другие.<br>Будет использован <b>глобальный</b> контекст, т.е тот же, что доступен в самих темплейтах.<br><br>Ps: рендеринг происходит на каждой странице отдельно через специальный template-тег. Это значит, что если вы используете НЕ стандартный темплейт (<code>core/generic/page.html</code>), товключение этой функции здесь <b>не гарантирует</b>, что оно подключено фронтендером ввыбанном темплейте <i>там</i>. Обсуждайте это совместно с тем, кто создаёт темплейты.<br><br>PPs: если вы используете стандартный template <code>core/generic/page.html</code>, беспокоится вам не о чем.', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. Также является значением по умолчанию для HTML Title.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется H1 или Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='render_content',
            field=models.BooleanField(default=False, verbose_name='Использовать рендеринг для content?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_name',
            field=models.CharField(default='core/generic/page.html', help_text='Путь к файлу, включая расширение', validators=[shared.models.validators.template_with_this_name_exists], verbose_name='Название django-темплейта'),
        ),
    ]
