# Generated by Django 5.2.5 on 2025-08-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_page_render_content_alter_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
    ]
