# Generated by Django 5.2.5 on 2025-08-28 09:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_page_h1_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Поддерживается django template рендеринг!<details style="width: 70%"><summary>Подробнее</summary><br>\n\t\tЕсли активирован рендеринг, текст из этого поля будет обработан через django template рендеринг.<br>\n\t\tЭто означает, что вы можете использовать здесь темплейт инструменты, такие как:\n\t\t<li>Теги <code>{% if %}</code>, <code>{% for %}</code> и другие.</li>\n\t\t<li>\n\t\t\tПеременные, например: <code>{{ page.extra_context }},\n\t\t\t{{ global.pages.home }}, {{ global.extra_context }}</code> и т.д.\n\t\t</li>\n\t\t<li>\n\t\t\tА также теги обработки, например: <code>...|default:"..."</code>,\n\t\t\t<code>...|truncatechars:40</code> и многие другие.\n\t\t</li>\n\t\tКонтекст будет такой же, как и на странице, на которой будет выводится этот текст.<br>\n\n\t\tВажно: функционал рендеринга реализуется в каждом темплейте отдельно, через специальный template-тег.\n\t\tЭто означает, что <b>нет гарантии</b>, что фронтендер добавил эту обработу <i>там</i>.\n\t\tСогласуйте это вместе с фронтендером.<br>Если же вы используете стандартный темплейт <code>core/generic/page.html</code>,то рендеринг гарантирован.</details>', verbose_name='Контент'),
        ),
    ]
