# Generated by Django 5.2.5 on 2025-09-04 05:44

import django.db.models.deletion
import pathlib
import shared.models.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('core', '0028_alter_page_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycontacts',
            options={'verbose_name': '📠 | Контакты компании'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'страница', 'verbose_name_plural': 'страницы'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': '⚙ | Настройки сайта'},
        ),
        migrations.AlterModelOptions(
            name='telegramsendingchannel',
            options={'verbose_name': 'Канал отправки сообщений в Telegram', 'verbose_name_plural': '📡 | Каналы отправки сообщений в Telegram'},
        ),
        migrations.AddField(
            model_name='page',
            name='previous_page_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='page',
            name='previous_page_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Поддерживается django template рендеринг!<details style="width: 70%; padding-left: 1rem;"><summary style="margin-left: -1rem;">Подробнее</summary>\n\t\tЕсли активирован рендеринг, текст из этого поля будет обработан через django template рендеринг.<br>\n\t\tЭто означает, что вы можете использовать здесь темплейт инструменты, такие как:\n\t\t<li>Теги <code>{% if %}</code>, <code>{% for %}</code> и другие.</li>\n\t\t<li>\n\t\t\tПеременные, например: <code>{{ page.extra_context }},\n\t\t\t{{ global.pages.home }}, {{ global.extra_context }}</code> и т.д.\n\t\t</li>\n\t\t<li>\n\t\t\tА также теги обработки, например: <code>...|default:"..."</code>,\n\t\t\t <code>...|truncatechars:40</code> и многие другие.\n\t\t</li>\n\t\tКонтекст будет такой же, как и на странице, на которой будет выводится этот текст.<br>\n\n\t\tВажно: функционал рендеринга реализуется в каждом темплейте отдельно, через специальный template-тег.\n\t\tЭто означает, что <b>нет гарантии</b>, что фронтендер добавил эту обработу <i>там</i>.\n\t\tСогласуйте это вместе с фронтендером.<br>Если же вы используете стандартный темплейт <code>core/generic/page.html</code>, то рендеринг гарантирован.</details>', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_generic_page',
            field=models.BooleanField(default=False, help_text='✅: Будет автоматически доступно по указанному url, требует заданного <code>template_name</code>. Используйте для простых страниц, не требующих своего View.<br>❌: Выбирайте, когда для обработки страницы нужно использовать кастомный view.<br><br>Влияет на работу логики поля <code>URL path</code> & <code>template_name</code>.', verbose_name='Это динамически-добавляемая страница?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_name',
            field=models.CharField(blank=True, help_text='<code>is_generic_page:</code>✅ - Путь к файлу, включая расширение, <b>должно быть установленно</b>.<br><code>is_generic_page:</code>❌ - Игнорируется, потому <b>должно быть</b> пустым.', validators=[shared.models.validators.template_with_this_name_exists], verbose_name='Название django-темплейта'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url_path',
            field=models.CharField(blank=True, help_text='<details style="padding-left: 1rem;"><summary style="margin-left: -1rem;"><code>is_generic_page</code>: ✅</summary>URL путь, по которому будет доступна страница. Указав <code>info/about-us/</code> здесь, страница будет доступна по адресу <code>/info/about-us/</code>.<br><b><u>Крайне рекомендуется</u></b> создавать url <u>на основе slug</u>. Например, при slug = <code>about-us</code>, url = <code>info/about-us/</code>).<br><br></details><details style="padding-left: 1rem;"><summary style="margin-left: -1rem;"><code>is_generic_page</code>: ❌</summary>Название <b>должно</b> соответствовать адресу, по которому можно перейти на страницу по кастомному view.<br>При ненахождении страницы по указанному url - сохранить изменения / создать страницу не удастся.<br></details><br><b>Всегда</b> отражает реальный адрес страницы.', max_length=64, unique=True, validators=[shared.models.validators.StringStartswith('/', invert=True), shared.models.validators.StringEndswith('/')], verbose_name='URL путь'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/_b.VV/_Learn/TLTConvectorTraining/media/favicon')),
        ),
    ]
