# Generated by Django 5.2.5 on 2025-09-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_companycontacts_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='previous_page_content_type',
        ),
        migrations.RemoveField(
            model_name='page',
            name='previous_page_id',
        ),
    ]
