# Generated by Django 5.2.5 on 2025-09-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_page_previous_page_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url_path',
            field=models.CharField(blank=True, help_text='<details style="padding-left: 1rem;"><summary style="margin-left: -1rem;"><code>is_generic_page</code>: ✅</summary>Полный URL путь, по которому будет доступна страница. Указав <code>info/about-us/</code> здесь, страница будет доступна по абсолютному пути <code>/info/about-us/</code><br><code>get_absolute_url()</code> вернёт <code>"/info/about-us/"</code>.<br><b><u>Крайне рекомендуется</u></b> создавать url <u>на основе <code>slug</code></u>. Например, при slug = <code>about-us</code>, url = <code>info/about-us/</code>).<br><br></details><details style="padding-left: 1rem;"><summary style="margin-left: -1rem;"><code>is_generic_page</code>: ❌</summary>View name того view, который обрабатывает эту страницу.<br>Например, в <code>urlpatterns</code> указан <code>path("fun-path/", ..., name="your-name")</code>, тут указываете <code>"your-name"</code>.<br><code>get_absolute_url()</code> вернёт <code>"/fun-path/"</code>.</details><br>Используется для получения url страницы в методе <code>get_absolute_url()</code>.<br>Также значение в этом поле валидируется и проходит проверку на корректность.', max_length=64, unique=True, verbose_name='URL Source'),
        ),
    ]
