# Generated by Django 5.2.5 on 2025-09-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_page_url_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url_path',
            new_name='url_source',
        ),
    ]
