# Generated by Django 5.2.5 on 2025-09-10 18:44

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_url_path_page_url_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='html_description',
            new_name='html_description_override',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Users/Admin/source/repos/TLTConvectorTraining/media/favicon')),
        ),
    ]
