# Generated by Django 5.2.5 on 2025-08-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='comment',
        ),
    ]
