# Generated by Django 5.2.5 on 2025-08-07 08:18

import django.db.models.deletion
import mptt.fields
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/categories/images'), verbose_name='Изображение')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название')),
                ('is_parent_category', models.BooleanField(default=True, help_text='✅: Можно разместить подкатегории, нельзя разместить товары.<br>❌: Можно разместить товары, нельзя разместить подкатегории.', verbose_name='Это родительская категория?')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='business.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
