# Generated by Django 5.2.6 on 2025-09-25 07:55

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/commercial-projects/TTSTempering/media/images/articles')),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/commercial-projects/TTSTempering/media/images/categories'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='performedserviceexample',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/commercial-projects/TTSTempering/media/images/services/examples'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blueprint_image',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/_b.VV/commercial-projects/TTSTempering/media/images/products/blueprints'), verbose_name='Чертёж'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/commercial-projects/TTSTempering/media/images/products/photos'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/commercial-projects/TTSTempering/media/images/services'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='serviceadvantage',
            name='image',
            field=models.ImageField(max_length=200, upload_to=pathlib.PureWindowsPath('C:/_b.VV/commercial-projects/TTSTempering/media/images/services/advantages'), verbose_name='Изображение'),
        ),
    ]
