# Generated by Django 5.2.5 on 2025-08-07 12:44

import ckeditor.fields
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacteristicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Тип характеристики')),
                ('unit_of_measurement', models.CharField(blank=True, help_text='Например: "мм", "лет", "МПа", "C°" и так далее.', max_length=12, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Типы характеристик',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('image', models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/images/services'), verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/images/articles')),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/images/categories'), verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('blueprint_image', models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/images/products/blueprints'), verbose_name='Чертёж')),
                ('sub_models_table', ckeditor.fields.RichTextField(blank=True, help_text='Создайте и заполните HTML таблицу с под-моделями товара', verbose_name='Таблица под-моделей товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdditionalElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_elements', to='business.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/images/products/photos'))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='business.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='PerformedServiceExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/images/services/examples'), verbose_name='Изображение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='business.service', verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=24, verbose_name='Значение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='business.product', verbose_name='Продукт')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.productcharacteristictype', verbose_name='Тип')),
            ],
            options={
                'unique_together': {('product', 'type')},
            },
        ),
    ]
