# Generated by Django 5.2.5 on 2025-08-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='html_description',
            field=models.CharField(blank=True, verbose_name='HTML Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для формирования HTML Title используется verbose_name.Укажите здесь свой title, и он будет использован вместо него.', max_length=128, verbose_name='HTML Title override'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='service', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется и для формирования HTML Title', max_length=64, verbose_name='Название'),
        ),
    ]
