# Generated by Django 5.2.6 on 2025-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_article_last_modified_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html_description',
            field=models.TextField(blank=True, verbose_name='HTML Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='html_description',
            field=models.TextField(blank=True, verbose_name='HTML Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_description',
            field=models.TextField(blank=True, verbose_name='HTML Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='html_description',
            field=models.TextField(blank=True, verbose_name='HTML Description'),
        ),
    ]
