# Generated by Django 5.2.6 on 2025-09-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_article_html_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='h1_override',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='html_title_override',
            new_name='html_title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='h1_override',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='html_title_override',
            new_name='html_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='h1_override',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='h1_override',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='html_title_override',
            new_name='html_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='html_title_override',
        ),
    ]
