# Generated by Django 5.2.6 on 2025-09-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_rename_h1_override_article_h1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='h1',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_title',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='h1',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='html_title',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='h1',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='h1',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок'),
        ),
        migrations.AlterField(
            model_name='service',
            name='html_title',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title'),
        ),
    ]
