# Generated by Django 5.2.5 on 2025-08-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_product_html_description_product_html_title_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_description',
            field=models.CharField(blank=True, verbose_name='HTML Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для формирования HTML Title используется verbose_name.Укажите здесь свой title, и он будет использован вместо него.', max_length=128, verbose_name='HTML Title override'),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='Статья', help_text='Указывайте человеко-читаемый текст. По умолчанию также используется и для формирования HTML Title', max_length=64, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='html_description',
            field=models.CharField(blank=True, verbose_name='HTML Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для формирования HTML Title используется verbose_name.Укажите здесь свой title, и он будет использован вместо него.', max_length=128, verbose_name='HTML Title override'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='summary',
            field=models.TextField(default='summary', help_text='Отображается на странице всех услуг в списке услуг', max_length=768, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется и для формирования HTML Title', max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
