# Generated by Django 5.2.6 on 2025-09-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_article_h1_alter_article_html_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='add_sitename_to_html_title',
            field=models.BooleanField(default=True, verbose_name='Добавить название сайта к HTML Title?'),
        ),
        migrations.AddField(
            model_name='category',
            name='add_sitename_to_html_title',
            field=models.BooleanField(default=True, verbose_name='Добавить название сайта к HTML Title?'),
        ),
        migrations.AddField(
            model_name='product',
            name='add_sitename_to_html_title',
            field=models.BooleanField(default=True, verbose_name='Добавить название сайта к HTML Title?'),
        ),
        migrations.AddField(
            model_name='service',
            name='add_sitename_to_html_title',
            field=models.BooleanField(default=True, verbose_name='Добавить название сайта к HTML Title?'),
        ),
    ]
