# Generated by Django 5.2.5 on 2025-08-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_article_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. ', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AddField(
            model_name='category',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. ', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AddField(
            model_name='product',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. ', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AddField(
            model_name='service',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. ', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется для HTML Title и H1.', max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется для HTML Title и H1.', max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется для HTML Title и H1.', max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Указывайте человеко-читаемый текст. По умолчанию также используется для HTML Title и H1.', max_length=64, verbose_name='Название'),
        ),
    ]
