# Generated by Django 5.2.6 on 2025-10-01 09:50

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_article_add_sitename_to_html_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childrens', to='business.category', verbose_name='Родительская категория'),
        ),
    ]
