# Generated by Django 5.2.5 on 2025-08-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_article_h1_override_category_h1_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
