# Generated by Django 5.2.5 on 2025-08-27 09:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Краткая информация о категории', max_length=1024, verbose_name='Краткое описание (summary)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. Также является значением по умолчанию для HTML Title.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется H1 или Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. Также является значением по умолчанию для HTML Title.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется H1 или Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. Также является значением по умолчанию для HTML Title.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется H1 или Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name. Также является значением по умолчанию для HTML Title.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется H1 или Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
    ]
