# Generated by Django 5.2.5 on 2025-08-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_category_summary_alter_article_h1_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='summary',
            field=models.TextField(blank=True, help_text='Краткая информация о категории', max_length=1024, verbose_name='Краткое описание (summary)'),
        ),
    ]
