# Generated by Django 5.2.5 on 2025-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_category_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='productcharacteristictype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название типа характеристики'),
        ),
        migrations.AlterField(
            model_name='productcharacteristictype',
            name='unit_of_measurement',
            field=models.CharField(blank=True, help_text='Например: "мм", "лет", "МПа", "C°" и так далее. Можно оставить пустым.', max_length=24, verbose_name='Единицы измерения'),
        ),
    ]
