# Generated by Django 5.2.5 on 2025-08-27 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_elements_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание в разделе дополнительных элементов и комплектации'),
        ),
    ]
