# Generated by Django 5.2.5 on 2025-08-27 12:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_product_additional_elements_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcharacteristictype',
            options={'ordering': ['name', 'unit_of_measurement'], 'verbose_name': 'Тип характеристики', 'verbose_name_plural': 'Типы характеристик'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержимое'),
        ),
    ]
