# Generated by Django 5.2.5 on 2025-08-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_article_content_serviceadvantage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceadvantage',
            options={'ordering': None, 'verbose_name': 'Преимущество услуги', 'verbose_name_plural': 'Преимущества услуги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='h1_override',
            field=models.CharField(blank=True, help_text='По умолчанию для H1 используется Name.', max_length=127, verbose_name='H1 Заголовок (переопределение)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='html_title_override',
            field=models.CharField(blank=True, help_text='По умолчанию для HTML Title используется Name.', max_length=128, verbose_name='HTML Title (переопределение)'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='serviceadvantage',
            order_with_respect_to='service',
        ),
    ]
