# Generated by Django 5.2.5 on 2025-08-28 09:44

import pathlib
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_serviceadvantage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='category',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, help_text='Краткая информация о категории', max_length=1024, verbose_name='Краткое описание (summary)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_elements_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание в разделе дополнительных элементов и комплектации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_models_table',
            field=tinymce.models.HTMLField(blank=True, help_text='Создайте и заполните HTML таблицу с под-моделями товара', verbose_name='Таблица под-моделей товара'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='summary',
            field=tinymce.models.HTMLField(help_text='Отображается на странице всех услуг в списке услуг', max_length=768, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='serviceadvantage',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='serviceadvantage',
            name='image',
            field=models.ImageField(max_length=200, upload_to=pathlib.PureWindowsPath('C:/Users/User/Desktop/_b.VV/_Learn/TLTConvectorTraining/media/images/services/advantages'), verbose_name='Изображение'),
        ),
    ]
