# Generated by Django 5.2.5 on 2025-08-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_article_content_alter_category_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceadvantage',
            options={'verbose_name': 'Преимущество услуги', 'verbose_name_plural': 'Преимущества услуги'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='serviceadvantage',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='serviceadvantage',
            name='order',
        ),
    ]
