# Generated by Django 5.2.5 on 2025-09-04 05:45

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_alter_serviceadvantage_options_and_more'),
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='article',
            name='previous_page_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='article',
            name='previous_page_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='previous_page_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='category',
            name='previous_page_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_page_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='previous_page_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='previous_page_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='service',
            name='previous_page_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/_Learn/TLTConvectorTraining/media/images/articles')),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/_Learn/TLTConvectorTraining/media/images/categories'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='performedserviceexample',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/_Learn/TLTConvectorTraining/media/images/services/examples'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blueprint_image',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/_b.VV/_Learn/TLTConvectorTraining/media/images/products/blueprints'), verbose_name='Чертёж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_parent_category': False}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/_Learn/TLTConvectorTraining/media/images/products/photos'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/_b.VV/_Learn/TLTConvectorTraining/media/images/services'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='serviceadvantage',
            name='image',
            field=models.ImageField(max_length=200, upload_to=pathlib.PureWindowsPath('C:/_b.VV/_Learn/TLTConvectorTraining/media/images/services/advantages'), verbose_name='Изображение'),
        ),
    ]
