# Generated by Django 5.2.5 on 2025-09-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='previous_page_content_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='previous_page_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='previous_page_content_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='previous_page_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_page_content_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='previous_page_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='previous_page_content_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='previous_page_id',
        ),
    ]
