# Generated by Django 5.2.5 on 2025-09-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_remove_article_previous_page_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(blank=True, null=True, verbose_name='В наличии'),
        ),
    ]
