# Generated by Django 5.2.5 on 2025-09-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_alter_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
    ]
