# Generated by Django 5.2.5 on 2025-09-10 18:44

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_remove_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='h1_override',
        ),
        migrations.RemoveField(
            model_name='article',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='html_title_override',
        ),
        migrations.RemoveField(
            model_name='category',
            name='h1_override',
        ),
        migrations.RemoveField(
            model_name='category',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='html_title_override',
        ),
        migrations.RemoveField(
            model_name='product',
            name='h1_override',
        ),
        migrations.RemoveField(
            model_name='product',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='html_title_override',
        ),
        migrations.RemoveField(
            model_name='service',
            name='h1_override',
        ),
        migrations.RemoveField(
            model_name='service',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='html_title_override',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Admin/source/repos/TLTConvectorTraining/media/images/articles')),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Admin/source/repos/TLTConvectorTraining/media/images/categories'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='performedserviceexample',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Admin/source/repos/TLTConvectorTraining/media/images/services/examples'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blueprint_image',
            field=models.ImageField(blank=True, upload_to=pathlib.PureWindowsPath('C:/Users/Admin/source/repos/TLTConvectorTraining/media/images/products/blueprints'), verbose_name='Чертёж'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Admin/source/repos/TLTConvectorTraining/media/images/products/photos'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/Admin/source/repos/TLTConvectorTraining/media/images/services'), verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='serviceadvantage',
            name='image',
            field=models.ImageField(max_length=200, upload_to=pathlib.PureWindowsPath('C:/Users/Admin/source/repos/TLTConvectorTraining/media/images/services/advantages'), verbose_name='Изображение'),
        ),
    ]
